### ISSUE TITLE
Add in link to checklist and slacks in Advance Work

### ISSUE THREAD

**Issue by dcwalk** [datarefuge/workflow#13]
In [advance-work.md](https://github.com/datarefugephilly/workflow/blob/master/advance-work.md), could be good to have:

- [ ] link to the [EDGI overview with outcomes from previous events](https://github.com/edgi-govdata-archiving/overview)
- [ ] link to the [pre-event checklist](https://github.com/edgi-govdata-archiving/overview/blob/master/CHECKLIST.md)
- [ ] link to the [EDGI toolkit](https://envirodatagov.org/event-toolkit/)

**Comment by khdelphine** [comment]
Yes, please, could you add them? (You will be a better judge of the best location for each one.) Thanks!

**Comment by librlaurie** [comment]
@dcwalk just pinging you here.

**Comment by dcwalk** [comment]
Closing per ongoing revamp conversation
